### ISSUE TITLE
Consider downloading a JDK even if JAVA_HOME is set

### ISSUE THREAD

**Issue by hakanai** [rmee/gradle-plugins#37]
We decided to modify the bootstrap a little locally.

```
JAVA_HOME="${JDK_CACHE_DIR}/jdk-${JDK_VERSION}";
# if [ -z "${JAVA_HOME}" ]; then
#	JAVA_HOME="${JDK_CACHE_DIR}/jdk-${JDK_VERSION}";
# fi
```

I don't know whether this would be globally loved, though. The issue in our case was that `JAVA_HOME` always points to Java 8, but I definitely want to build with Java 11. I guess a 100% "nice" solution would be to accept the existing `JAVA_HOME` if it happens to point to the right version, but it seemed like a tricky thing to pull off.

Perhaps a compromise could be a boolean property which decides whether to accept `JAVA_HOME` or not, so that people can turn it off or leave it alone?

**Comment by remmeier** [comment]
done & released
